### ISSUE TITLE
sharplinter should not validate jslint/jshint options

### ISSUE THREAD

**Issue by katlimruiz** [jamietre/SharpLinter#10]
it should just assume these are correct, because new versions of jshint/jslint would break this.

**Comment by katlimruiz** [comment]
I ended up forking, and make a pull request to update the latest jshint options.

But still I think this should be a command line option for future-proof the code

**Comment by jamietre** [comment]
I agree- I haven't done any work on this in a long time,  but if you want to push changes I'm glad to merge them.

**Comment by katlimruiz** [comment]
thanks jamietre, question: is there anything needed from me to publish the code officially?
