### ISSUE TITLE
Using new JSHint.js

### ISSUE THREAD

**Issue by alaney** [jamietre/SharpLinter#17]
Is it possible to use the newest version of JShint.js from (https://raw.githubusercontent.com/jshint/jshint/master/dist/jshint.js)? I would like to have options like camelcase and strict available. Right now if I use the newest JShint options like camelcase are still not available. Any help is greatly appreciated.

**Comment by jamietre** [comment]
You should be able to just drop in any version of jshint/jslint into the same folder where SharpLinter is running, just be sure it's named "jslint.js". It will use that code automatically. See the `-j` option description.

**Comment by Baidaly** [comment]
Sorry, but I guess the question is, are you going keep JsLint and JsHint up to date? Or can we push new pull requests of new JsLint and JsHint versions?

**Comment by jamietre** [comment]
See the previous comment. You can use any version of jshint or jslint that you want by just dropping into into the same folder and naming it "jslint.js". I'm happy you should issue pull requests with new versions, but the whole idea of this architecture was that you're not limited to using the version it was compiled using, that's just a fallback.

**Comment by Baidaly** [comment]
Makes sense. I guess this issue can be closed. 

BTW, I used this project to make JsLint Check-In policy for TFS. I'd really appreciate if you put the link to that project: https://github.com/Baidaly/JsLintPolicy

Thank you for your work!

**Comment by jamietre** [comment]
Sure, I don't have a good sense for where that link should go, since I don't have anything other than a readme! What were you thinking..

**Comment by Baidaly** [comment]
I guess the README file is more than enough :)
